import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";
import { BarbaWrapper, Navbar } from "@/components/commons";



const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Forgenest Services Pvt. Ltd.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${oswald.variable} font-sans antialiased`}>
        <Navbar />
        <BarbaWrapper>
          {children}
        </BarbaWrapper>
      </body>
    </html>
  );
}
